# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 8",
   "iPhone 8 Plus"
 ])

languages([
   "en-US"
])

scheme("screenShotUITests")

output_directory("./screenshots")

clear_previous_screenshots(true)



# For more information about all available options run
# fastlane action snapshot
